sudo: required
services:
    - docker

before_install: 
    - docker build -t kanababa1723/react-test -f ./client/Dockerfile.dev .

script:
    - docker run -e CI=true kanababa1723/react-test npm test

after_success:
    - docker build -t kanababa1723/multi-client ./client
    - docker build -t kanababa1723/multi-nginx ./nginx
    - docker build -t kanababa1723/multi-server ./server
    - docker build -t kanababa1723/multi-worker ./worker
    # login to docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # take those images and push to dockerhub
    - docker push kanababa1723/multi-client
    - docker push kanababa1723/multi-nginx
    - docker push kanababa1723/multi-server
    - docker push kanababa1723/multi-worker

